#! bin/bash
##SET REQUIRED PASSWORDS

##SET VENUE NAME AND VENUE DISPLAY NAME: 
##VENUE SHOULD BE THE VENUE NAME AND POSTCODE WITH ANY SPACES REPLACED BY _ AND ANY APOSTROPHES REPLACED BY 1
##VENUE DISPLAY TITLE SHOULD EXACTLY HOW THE CUSTOMER SHOULD SEE THE NAME

VENUE="Matt1s_Bar_PE27_6TN"
VENUE_DISPLAY="Matt's Bar"

#SQL database host, port, username and password

SQL_ENDPOINT="localhost"
SQL_PORT=3306
MY_UID="firstUser241"
MY_PWD="radiatorBarking939!"

#VENUE LOGIN PASSWORD FOR PUBEND AND CHECKCLOSED APPS

VENUE_PASSWORD="mypassword"

#SET SECURITY TOKEN (ADDITIONAL INFO FOR PULLING NHS TRACK & TRACE INFO

SECURITY_TOKEN="1359977526"
